import type { BotThreadState } from "@/types";

export const BOT_STATE_DEFAULT: BotThreadState = {
  awaiting: null,
  lastProductSlug: null,
  mode: "bot",
};

export const HELP_MESSAGE = [
  "Posso te ajudar com:",
  "- Listar produtos do catalogo",
  "- Consultar preco",
  "- Verificar disponibilidade e estoque",
  "- Mostrar o produto mais barato",
  "- Encaminhar para um atendente humano",
  "",
  "Exemplos:",
  '- "Quais produtos voces tem?"',
  '- "Quanto custa o moedor manual preto?"',
  '- "Tem camiseta bora de cafe em estoque?"',
].join("\n");

export const PRODUCT_QUERY_NOISE = new Set([
  "a",
  "ao",
  "as",
  "com",
  "consulta",
  "consultar",
  "custa",
  "da",
  "de",
  "detalhes",
  "disponibilidade",
  "disponivel",
  "do",
  "dos",
  "e",
  "em",
  "estoque",
  "favor",
  "me",
  "mostrar",
  "mostra",
  "o",
  "os",
  "para",
  "preco",
  "produto",
  "produtos",
  "qual",
  "quais",
  "quanto",
  "quero",
  "saber",
  "sobre",
  "tem",
  "um",
  "uma",
  "valor",
  "ver",
  "voces",
  "voce",
]);
